// Auto-generated by scripts/fetch-gallery.mjs — do not edit manually
// Run `npm run fetch-gallery` to refresh from Google Drive.

export interface GalleryItem {
  id:          string;
  img:         string;
  url:         string;
  height:      number;
  description: string;
}

export interface GalleryFolder {
  id:          string;
  name:        string;
  description: string;
}

export interface GalleryGroup {
  /** null = root-level images (no section header) */
  folder: GalleryFolder | null;
  items:  GalleryItem[];
}

export const galleryGroups: GalleryGroup[] = [
  {
    "folder": null,
    "items": [
      {
        "id": "1YyUQ_xrgE-UaXW7XHFegCcSBHKnyqjZ3",
        "img": "/gallery/1YyUQ_xrgE-UaXW7XHFegCcSBHKnyqjZ3.heic",
        "url": "https://drive.google.com/file/d/1YyUQ_xrgE-UaXW7XHFegCcSBHKnyqjZ3/view",
        "height": 450,
        "description": ""
      },
      {
        "id": "1cc9-HEsbnxPoThg39Hsp-KjpacRcl8sI",
        "img": "/gallery/1cc9-HEsbnxPoThg39Hsp-KjpacRcl8sI.heic",
        "url": "https://drive.google.com/file/d/1cc9-HEsbnxPoThg39Hsp-KjpacRcl8sI/view",
        "height": 450,
        "description": ""
      },
      {
        "id": "1dMICLqybMjckutGImvtcuMO3aPvbADKC",
        "img": "/gallery/1dMICLqybMjckutGImvtcuMO3aPvbADKC.heic",
        "url": "https://drive.google.com/file/d/1dMICLqybMjckutGImvtcuMO3aPvbADKC/view",
        "height": 450,
        "description": ""
      },
      {
        "id": "1TLFkBhOAAcnPTszFElf1XzvTOzA3hYAb",
        "img": "/gallery/1TLFkBhOAAcnPTszFElf1XzvTOzA3hYAb.gif",
        "url": "https://drive.google.com/file/d/1TLFkBhOAAcnPTszFElf1XzvTOzA3hYAb/view",
        "height": 1046,
        "description": ""
      },
      {
        "id": "1kZfuVaCZKUgifNTlH9vPSCZ29d-CFQ0S",
        "img": "/gallery/1kZfuVaCZKUgifNTlH9vPSCZ29d-CFQ0S.gif",
        "url": "https://drive.google.com/file/d/1kZfuVaCZKUgifNTlH9vPSCZ29d-CFQ0S/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1ezVNYAOz0AkjBU6esrksukAQSE1P1mMO",
        "img": "/gallery/1ezVNYAOz0AkjBU6esrksukAQSE1P1mMO.gif",
        "url": "https://drive.google.com/file/d/1ezVNYAOz0AkjBU6esrksukAQSE1P1mMO/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1J4xSvsxmEPOzIITDbZU3BXd09_56rHQT",
        "img": "/gallery/1J4xSvsxmEPOzIITDbZU3BXd09_56rHQT.gif",
        "url": "https://drive.google.com/file/d/1J4xSvsxmEPOzIITDbZU3BXd09_56rHQT/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1vpuSfPiNzQHj6SazKJn17XoZYvfHsx8o",
        "img": "/gallery/1vpuSfPiNzQHj6SazKJn17XoZYvfHsx8o.gif",
        "url": "https://drive.google.com/file/d/1vpuSfPiNzQHj6SazKJn17XoZYvfHsx8o/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1IchZJS1Uk8GUlSyrZjnmLl3QX3wTALgD",
        "img": "/gallery/1IchZJS1Uk8GUlSyrZjnmLl3QX3wTALgD.gif",
        "url": "https://drive.google.com/file/d/1IchZJS1Uk8GUlSyrZjnmLl3QX3wTALgD/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1n6MfERSRNWSKNjv8I9bZUBh-7FYG-Y-e",
        "img": "/gallery/1n6MfERSRNWSKNjv8I9bZUBh-7FYG-Y-e.gif",
        "url": "https://drive.google.com/file/d/1n6MfERSRNWSKNjv8I9bZUBh-7FYG-Y-e/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1MW5iLC8rTJrOClVVFiUJQCLy2UT0pIGP",
        "img": "/gallery/1MW5iLC8rTJrOClVVFiUJQCLy2UT0pIGP.gif",
        "url": "https://drive.google.com/file/d/1MW5iLC8rTJrOClVVFiUJQCLy2UT0pIGP/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "18I5_Vy-IugVzGBjAqamaFhBcntVCPfaI",
        "img": "/gallery/18I5_Vy-IugVzGBjAqamaFhBcntVCPfaI.gif",
        "url": "https://drive.google.com/file/d/18I5_Vy-IugVzGBjAqamaFhBcntVCPfaI/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1Dehbp2k17ET3kR_R0Hzz9BCCibwmLpki",
        "img": "/gallery/1Dehbp2k17ET3kR_R0Hzz9BCCibwmLpki.gif",
        "url": "https://drive.google.com/file/d/1Dehbp2k17ET3kR_R0Hzz9BCCibwmLpki/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1fMSGOO52hYCaXqYvDLrgVHwizThuSfU9",
        "img": "/gallery/1fMSGOO52hYCaXqYvDLrgVHwizThuSfU9.gif",
        "url": "https://drive.google.com/file/d/1fMSGOO52hYCaXqYvDLrgVHwizThuSfU9/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1p-BP33EhIOLvrC25GhieImpeAad3tHSm",
        "img": "/gallery/1p-BP33EhIOLvrC25GhieImpeAad3tHSm.gif",
        "url": "https://drive.google.com/file/d/1p-BP33EhIOLvrC25GhieImpeAad3tHSm/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1grENPZmGfb1k7JOCf3ojDyPxpikvD9oq",
        "img": "/gallery/1grENPZmGfb1k7JOCf3ojDyPxpikvD9oq.gif",
        "url": "https://drive.google.com/file/d/1grENPZmGfb1k7JOCf3ojDyPxpikvD9oq/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1J3WivGwlINUhwapglroS6YnTfeggZGYi",
        "img": "/gallery/1J3WivGwlINUhwapglroS6YnTfeggZGYi.gif",
        "url": "https://drive.google.com/file/d/1J3WivGwlINUhwapglroS6YnTfeggZGYi/view",
        "height": 795,
        "description": ""
      },
      {
        "id": "19OaFd669y3aWB4gSHfqvLdphkmS7ffud",
        "img": "/gallery/19OaFd669y3aWB4gSHfqvLdphkmS7ffud.gif",
        "url": "https://drive.google.com/file/d/19OaFd669y3aWB4gSHfqvLdphkmS7ffud/view",
        "height": 602,
        "description": ""
      },
      {
        "id": "1vOXkgakKmQXHI1Df-XOKCu95zd0jAYpp",
        "img": "/gallery/1vOXkgakKmQXHI1Df-XOKCu95zd0jAYpp.gif",
        "url": "https://drive.google.com/file/d/1vOXkgakKmQXHI1Df-XOKCu95zd0jAYpp/view",
        "height": 822,
        "description": ""
      },
      {
        "id": "1LVLI4xSo2l7bWRBH8cf641CW68gQ3CIj",
        "img": "/gallery/1LVLI4xSo2l7bWRBH8cf641CW68gQ3CIj.gif",
        "url": "https://drive.google.com/file/d/1LVLI4xSo2l7bWRBH8cf641CW68gQ3CIj/view",
        "height": 215,
        "description": ""
      },
      {
        "id": "1LTECyUHHn6EH9eo59bxT08bhjFZA-i_2",
        "img": "/gallery/1LTECyUHHn6EH9eo59bxT08bhjFZA-i_2.png",
        "url": "https://drive.google.com/file/d/1LTECyUHHn6EH9eo59bxT08bhjFZA-i_2/view",
        "height": 201,
        "description": ""
      },
      {
        "id": "112M90OG8bCr7UobvR0Rcz1us4mlj4wFX",
        "img": "/gallery/112M90OG8bCr7UobvR0Rcz1us4mlj4wFX.png",
        "url": "https://drive.google.com/file/d/112M90OG8bCr7UobvR0Rcz1us4mlj4wFX/view",
        "height": 202,
        "description": ""
      },
      {
        "id": "1LJ-TODUQOT2zlg5kHP5VnYM7pcZZN11N",
        "img": "/gallery/1LJ-TODUQOT2zlg5kHP5VnYM7pcZZN11N.png",
        "url": "https://drive.google.com/file/d/1LJ-TODUQOT2zlg5kHP5VnYM7pcZZN11N/view",
        "height": 686,
        "description": ""
      },
      {
        "id": "1YorOX71TYI-UqYyFRTW7bV_PfA9hMs7H",
        "img": "/gallery/1YorOX71TYI-UqYyFRTW7bV_PfA9hMs7H.png",
        "url": "https://drive.google.com/file/d/1YorOX71TYI-UqYyFRTW7bV_PfA9hMs7H/view",
        "height": 421,
        "description": ""
      },
      {
        "id": "1ErgQk7lIQXDLH8k-RGdazJkaPx3uvXLz",
        "img": "/gallery/1ErgQk7lIQXDLH8k-RGdazJkaPx3uvXLz.jpg",
        "url": "https://drive.google.com/file/d/1ErgQk7lIQXDLH8k-RGdazJkaPx3uvXLz/view",
        "height": 800,
        "description": ""
      },
      {
        "id": "15Qlc4bWRhgGDQJFjUf8N-fOwk5cKSY_r",
        "img": "/gallery/15Qlc4bWRhgGDQJFjUf8N-fOwk5cKSY_r.png",
        "url": "https://drive.google.com/file/d/15Qlc4bWRhgGDQJFjUf8N-fOwk5cKSY_r/view",
        "height": 1067,
        "description": ""
      },
      {
        "id": "1ZLBQHu4EHMT1jyVYaHyOMqy8CJqJ8TsL",
        "img": "/gallery/1ZLBQHu4EHMT1jyVYaHyOMqy8CJqJ8TsL.png",
        "url": "https://drive.google.com/file/d/1ZLBQHu4EHMT1jyVYaHyOMqy8CJqJ8TsL/view",
        "height": 877,
        "description": "meow meow dennis this is midnight update trigger. we will pay attention"
      }
    ]
  },
  {
    "folder": {
      "id": "1mBo0ta-e-wfBDJJVarW2uRaMjb_SJNTY",
      "name": "EXAMPLE",
      "description": "wooof wooof crystal"
    },
    "items": [
      {
        "id": "1HwFlVHKQkK0C4qpWR2zUX8QDaGkWtw0a",
        "img": "/gallery/1HwFlVHKQkK0C4qpWR2zUX8QDaGkWtw0a.gif",
        "url": "https://drive.google.com/file/d/1HwFlVHKQkK0C4qpWR2zUX8QDaGkWtw0a/view",
        "height": 800,
        "description": ""
      },
      {
        "id": "1ZCaEsaADVZ1q6npLNNw_YxIIKbbvyzHh",
        "img": "/gallery/1ZCaEsaADVZ1q6npLNNw_YxIIKbbvyzHh.png",
        "url": "https://drive.google.com/file/d/1ZCaEsaADVZ1q6npLNNw_YxIIKbbvyzHh/view",
        "height": 900,
        "description": ""
      }
    ]
  },
  {
    "folder": {
      "id": "10n4gX4u4FP3nFSPWkAG8dwYI05M0g4xb",
      "name": "grumpy",
      "description": ""
    },
    "items": [
      {
        "id": "1b_msDnELeNQMLXtbsy1fdjmWlci-9hE6",
        "img": "/gallery/1b_msDnELeNQMLXtbsy1fdjmWlci-9hE6.png",
        "url": "https://drive.google.com/file/d/1b_msDnELeNQMLXtbsy1fdjmWlci-9hE6/view",
        "height": 539,
        "description": ""
      },
      {
        "id": "1tPaAGJM8aysjLNGDJkrFgKjQgr21Quec",
        "img": "/gallery/1tPaAGJM8aysjLNGDJkrFgKjQgr21Quec.png",
        "url": "https://drive.google.com/file/d/1tPaAGJM8aysjLNGDJkrFgKjQgr21Quec/view",
        "height": 535,
        "description": ""
      }
    ]
  },
  {
    "folder": {
      "id": "17bDlg6Lfa4EFQss_4Tpd7HcwzHQ53yHQ",
      "name": "dev",
      "description": ""
    },
    "items": [
      {
        "id": "1RqfCZfSnAT0ePsJ1pvkxSL6MmnUY9yHP",
        "img": "/gallery/1RqfCZfSnAT0ePsJ1pvkxSL6MmnUY9yHP.png",
        "url": "https://drive.google.com/file/d/1RqfCZfSnAT0ePsJ1pvkxSL6MmnUY9yHP/view",
        "height": 424,
        "description": ""
      },
      {
        "id": "1PPLq69Ohm7XsUZzU8Zlmmg2JTtn0a-Df",
        "img": "/gallery/1PPLq69Ohm7XsUZzU8Zlmmg2JTtn0a-Df.png",
        "url": "https://drive.google.com/file/d/1PPLq69Ohm7XsUZzU8Zlmmg2JTtn0a-Df/view",
        "height": 424,
        "description": ""
      },
      {
        "id": "1l5tEIUU89Xll9x_tOzZDa6PVppg9F0j2",
        "img": "/gallery/1l5tEIUU89Xll9x_tOzZDa6PVppg9F0j2.png",
        "url": "https://drive.google.com/file/d/1l5tEIUU89Xll9x_tOzZDa6PVppg9F0j2/view",
        "height": 424,
        "description": ""
      },
      {
        "id": "1lR8fcaxQdFxboC9ojIrn044z79p8sdMw",
        "img": "/gallery/1lR8fcaxQdFxboC9ojIrn044z79p8sdMw.png",
        "url": "https://drive.google.com/file/d/1lR8fcaxQdFxboC9ojIrn044z79p8sdMw/view",
        "height": 424,
        "description": ""
      }
    ]
  },
  {
    "folder": {
      "id": "1qZrGxtxDgW5Ly5XdCqiQPAQ0VE_ZF-uw",
      "name": "olympics",
      "description": ""
    },
    "items": [
      {
        "id": "1vg9CiqLPtubhLDEAL_Sy4Ir_VKRvI9Wo",
        "img": "/gallery/1vg9CiqLPtubhLDEAL_Sy4Ir_VKRvI9Wo.gif",
        "url": "https://drive.google.com/file/d/1vg9CiqLPtubhLDEAL_Sy4Ir_VKRvI9Wo/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1k7bL9vqAnCROmvCXL8e_40g77_6Dsd3S",
        "img": "/gallery/1k7bL9vqAnCROmvCXL8e_40g77_6Dsd3S.png",
        "url": "https://drive.google.com/file/d/1k7bL9vqAnCROmvCXL8e_40g77_6Dsd3S/view",
        "height": 450,
        "description": ""
      },
      {
        "id": "1qHl2FxvUQAZ5EPHtoZfHjCbUDXQHy3AE",
        "img": "/gallery/1qHl2FxvUQAZ5EPHtoZfHjCbUDXQHy3AE.png",
        "url": "https://drive.google.com/file/d/1qHl2FxvUQAZ5EPHtoZfHjCbUDXQHy3AE/view",
        "height": 787,
        "description": ""
      },
      {
        "id": "1FOH2zHE7LuNFxlYIgSX3oy9eaPvbkM9P",
        "img": "/gallery/1FOH2zHE7LuNFxlYIgSX3oy9eaPvbkM9P.png",
        "url": "https://drive.google.com/file/d/1FOH2zHE7LuNFxlYIgSX3oy9eaPvbkM9P/view",
        "height": 800,
        "description": ""
      },
      {
        "id": "1XxsphQ4DR7vrmnqekAp1tlTU5sZhAoq7",
        "img": "/gallery/1XxsphQ4DR7vrmnqekAp1tlTU5sZhAoq7.png",
        "url": "https://drive.google.com/file/d/1XxsphQ4DR7vrmnqekAp1tlTU5sZhAoq7/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1ZTQOKPM4ZnQu_1JQJwzVsVOCKgdJi7zw",
        "img": "/gallery/1ZTQOKPM4ZnQu_1JQJwzVsVOCKgdJi7zw.png",
        "url": "https://drive.google.com/file/d/1ZTQOKPM4ZnQu_1JQJwzVsVOCKgdJi7zw/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1_McamqpP_pzVcYnwsu99rXRfWuINqgEh",
        "img": "/gallery/1_McamqpP_pzVcYnwsu99rXRfWuINqgEh.png",
        "url": "https://drive.google.com/file/d/1_McamqpP_pzVcYnwsu99rXRfWuINqgEh/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1DRWJlU8HgaqyD6K2IobVx-GD2keNpUOj",
        "img": "/gallery/1DRWJlU8HgaqyD6K2IobVx-GD2keNpUOj.png",
        "url": "https://drive.google.com/file/d/1DRWJlU8HgaqyD6K2IobVx-GD2keNpUOj/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1WYMmKo0TbdnXZag-vlS_V9qEJWS-Tt8w",
        "img": "/gallery/1WYMmKo0TbdnXZag-vlS_V9qEJWS-Tt8w.png",
        "url": "https://drive.google.com/file/d/1WYMmKo0TbdnXZag-vlS_V9qEJWS-Tt8w/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1h05DqbkLNlNJU5F1ncimVWC0dge3JLrL",
        "img": "/gallery/1h05DqbkLNlNJU5F1ncimVWC0dge3JLrL.png",
        "url": "https://drive.google.com/file/d/1h05DqbkLNlNJU5F1ncimVWC0dge3JLrL/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1zgXiz870qJFkRxrj3ZMaCpnlaKQyhMVa",
        "img": "/gallery/1zgXiz870qJFkRxrj3ZMaCpnlaKQyhMVa.png",
        "url": "https://drive.google.com/file/d/1zgXiz870qJFkRxrj3ZMaCpnlaKQyhMVa/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "17MCl7gl-UMOpkmpGw53VSU7Wy0JlWiFO",
        "img": "/gallery/17MCl7gl-UMOpkmpGw53VSU7Wy0JlWiFO.png",
        "url": "https://drive.google.com/file/d/17MCl7gl-UMOpkmpGw53VSU7Wy0JlWiFO/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1GGUiQyxxtoi6mE5KqIazMOlVr329TkVh",
        "img": "/gallery/1GGUiQyxxtoi6mE5KqIazMOlVr329TkVh.png",
        "url": "https://drive.google.com/file/d/1GGUiQyxxtoi6mE5KqIazMOlVr329TkVh/view",
        "height": 400,
        "description": ""
      }
    ]
  }
];

/** Flat list of all items (for backwards compatibility). */
export const galleryItems: GalleryItem[] = galleryGroups.flatMap(g => g.items);
