// Auto-generated by scripts/fetch-gallery.mjs — do not edit manually
// Run `npm run fetch-gallery` to refresh from Google Drive.

export interface GalleryItem {
  id:          string;
  img:         string;
  url:         string;
  height:      number;
  description: string;
}

export interface GalleryFolder {
  id:          string;
  name:        string;
  description: string;
}

export interface GalleryGroup {
  /** null = root-level images (no section header) */
  folder: GalleryFolder | null;
  items:  GalleryItem[];
}

export const galleryGroups: GalleryGroup[] = [
  {
    "folder": {
      "id": "1yRlo6MJ5_2QDEttMH7lOg1Er_dco8sUP",
      "name": "Chairish",
      "description": ""
    },
    "items": [
      {
        "id": "1xeK68pOKP5PCBsmHii1H6ho7FuWF99OS",
        "img": "/gallery/1xeK68pOKP5PCBsmHii1H6ho7FuWF99OS.jpeg",
        "url": "https://drive.google.com/file/d/1xeK68pOKP5PCBsmHii1H6ho7FuWF99OS/view",
        "height": 800,
        "description": ""
      },
      {
        "id": "1cjsp10IfcTvrTLfU98UWQf0TrbSRmXK0",
        "img": "/gallery/1cjsp10IfcTvrTLfU98UWQf0TrbSRmXK0.jpeg",
        "url": "https://drive.google.com/file/d/1cjsp10IfcTvrTLfU98UWQf0TrbSRmXK0/view",
        "height": 800,
        "description": ""
      },
      {
        "id": "1D-oDvRv0lS8vlfldvGj-if0mLHKXg_zJ",
        "img": "/gallery/1D-oDvRv0lS8vlfldvGj-if0mLHKXg_zJ.jpeg",
        "url": "https://drive.google.com/file/d/1D-oDvRv0lS8vlfldvGj-if0mLHKXg_zJ/view",
        "height": 800,
        "description": ""
      },
      {
        "id": "16URD60L49ZrTNA2vR2YKXDyR2ijVGoUa",
        "img": "/gallery/16URD60L49ZrTNA2vR2YKXDyR2ijVGoUa.jpeg",
        "url": "https://drive.google.com/file/d/16URD60L49ZrTNA2vR2YKXDyR2ijVGoUa/view",
        "height": 800,
        "description": ""
      },
      {
        "id": "1qZKxAgD-3amoIN6AwNaehb62s7IhMhkb",
        "img": "/gallery/1qZKxAgD-3amoIN6AwNaehb62s7IhMhkb.jpeg",
        "url": "https://drive.google.com/file/d/1qZKxAgD-3amoIN6AwNaehb62s7IhMhkb/view",
        "height": 800,
        "description": ""
      },
      {
        "id": "1AK3IJQ415O9lBv2RtYhat9UV56X2PHIa",
        "img": "/gallery/1AK3IJQ415O9lBv2RtYhat9UV56X2PHIa.png",
        "url": "https://drive.google.com/file/d/1AK3IJQ415O9lBv2RtYhat9UV56X2PHIa/view",
        "height": 710,
        "description": ""
      }
    ]
  },
  {
    "folder": {
      "id": "1A2rIYKKyfwd2-L_Ll-qYU5AGgww7eq-x",
      "name": "Social-Media",
      "description": ""
    },
    "items": [
      {
        "id": "1PV-KF1297_8VIIxcwT16q2ntYp66LMsc",
        "img": "/gallery/1PV-KF1297_8VIIxcwT16q2ntYp66LMsc.png",
        "url": "https://drive.google.com/file/d/1PV-KF1297_8VIIxcwT16q2ntYp66LMsc/view",
        "height": 197,
        "description": ""
      },
      {
        "id": "1d3tvOSQgWKAZnhV3NDEUTFp7SRrvIBMz",
        "img": "/gallery/1d3tvOSQgWKAZnhV3NDEUTFp7SRrvIBMz.png",
        "url": "https://drive.google.com/file/d/1d3tvOSQgWKAZnhV3NDEUTFp7SRrvIBMz/view",
        "height": 197,
        "description": ""
      },
      {
        "id": "1miHVpIPZKNsE2xdyyyCazlH2VKi69atT",
        "img": "/gallery/1miHVpIPZKNsE2xdyyyCazlH2VKi69atT.png",
        "url": "https://drive.google.com/file/d/1miHVpIPZKNsE2xdyyyCazlH2VKi69atT/view",
        "height": 197,
        "description": ""
      },
      {
        "id": "1smL62B7UuhShAiMHCK74oMMehHTNjJee",
        "img": "/gallery/1smL62B7UuhShAiMHCK74oMMehHTNjJee.png",
        "url": "https://drive.google.com/file/d/1smL62B7UuhShAiMHCK74oMMehHTNjJee/view",
        "height": 197,
        "description": ""
      },
      {
        "id": "1nHGMicG33oyea9iivEubrMGqMR12KHlh",
        "img": "/gallery/1nHGMicG33oyea9iivEubrMGqMR12KHlh.png",
        "url": "https://drive.google.com/file/d/1nHGMicG33oyea9iivEubrMGqMR12KHlh/view",
        "height": 197,
        "description": ""
      }
    ]
  },
  {
    "folder": {
      "id": "1lJlULJEO1GqalOqcnWhTN0JJ_C5Y4NXe",
      "name": "Why-Fish-Don't-Exist",
      "description": ""
    },
    "items": [
      {
        "id": "1JdWtyFCrgb4YYv6aNWDyUvyxmKiDb5vm",
        "img": "/gallery/1JdWtyFCrgb4YYv6aNWDyUvyxmKiDb5vm.png",
        "url": "https://drive.google.com/file/d/1JdWtyFCrgb4YYv6aNWDyUvyxmKiDb5vm/view",
        "height": 754,
        "description": ""
      },
      {
        "id": "1WgEav7xrNn_Wramv-OwzFiTjIstRO-lo",
        "img": "/gallery/1WgEav7xrNn_Wramv-OwzFiTjIstRO-lo.jpg",
        "url": "https://drive.google.com/file/d/1WgEav7xrNn_Wramv-OwzFiTjIstRO-lo/view",
        "height": 386,
        "description": ""
      }
    ]
  },
  {
    "folder": {
      "id": "13IvkRf_HZOguCnJWGi5FWlvB4YLno97w",
      "name": "He-Cha",
      "description": ""
    },
    "items": [
      {
        "id": "1Wcyc0wiieSy1l-zsg6mQwuEhIsVE-KTA",
        "img": "/gallery/1Wcyc0wiieSy1l-zsg6mQwuEhIsVE-KTA.png",
        "url": "https://drive.google.com/file/d/1Wcyc0wiieSy1l-zsg6mQwuEhIsVE-KTA/view",
        "height": 470,
        "description": ""
      },
      {
        "id": "1pyhQ85qEhuefEgr4XsbKXABC8zfNJxQP",
        "img": "/gallery/1pyhQ85qEhuefEgr4XsbKXABC8zfNJxQP.png",
        "url": "https://drive.google.com/file/d/1pyhQ85qEhuefEgr4XsbKXABC8zfNJxQP/view",
        "height": 465,
        "description": ""
      },
      {
        "id": "1sxUse5ZKiAhSb8kQSmnKli_z997UMCCW",
        "img": "/gallery/1sxUse5ZKiAhSb8kQSmnKli_z997UMCCW.png",
        "url": "https://drive.google.com/file/d/1sxUse5ZKiAhSb8kQSmnKli_z997UMCCW/view",
        "height": 444,
        "description": ""
      },
      {
        "id": "13thutyAc2Xgt0imSB-cGx6BFYht8jvp0",
        "img": "/gallery/13thutyAc2Xgt0imSB-cGx6BFYht8jvp0.png",
        "url": "https://drive.google.com/file/d/13thutyAc2Xgt0imSB-cGx6BFYht8jvp0/view",
        "height": 460,
        "description": ""
      },
      {
        "id": "1rxzlihiD-UCSHYuwx3PD7McP9lfEGeZW",
        "img": "/gallery/1rxzlihiD-UCSHYuwx3PD7McP9lfEGeZW.png",
        "url": "https://drive.google.com/file/d/1rxzlihiD-UCSHYuwx3PD7McP9lfEGeZW/view",
        "height": 589,
        "description": ""
      }
    ]
  },
  {
    "folder": {
      "id": "1iHJF0BuNdHykLyodak1lRHN22kuVIbXQ",
      "name": "GNTRF-Publication",
      "description": ""
    },
    "items": [
      {
        "id": "1ML2qcq-zL0hPt1FzC54FbmeetgwxM_fw",
        "img": "/gallery/1ML2qcq-zL0hPt1FzC54FbmeetgwxM_fw.jpeg",
        "url": "https://drive.google.com/file/d/1ML2qcq-zL0hPt1FzC54FbmeetgwxM_fw/view",
        "height": 450,
        "description": ""
      },
      {
        "id": "12aBy_XPiAPxawORQfSmFya4a9XyS7E_M",
        "img": "/gallery/12aBy_XPiAPxawORQfSmFya4a9XyS7E_M.jpeg",
        "url": "https://drive.google.com/file/d/12aBy_XPiAPxawORQfSmFya4a9XyS7E_M/view",
        "height": 450,
        "description": ""
      },
      {
        "id": "1IhdWdMsle-UbdvdTfBHIAFL1W9-HO2E2",
        "img": "/gallery/1IhdWdMsle-UbdvdTfBHIAFL1W9-HO2E2.jpeg",
        "url": "https://drive.google.com/file/d/1IhdWdMsle-UbdvdTfBHIAFL1W9-HO2E2/view",
        "height": 450,
        "description": ""
      }
    ]
  },
  {
    "folder": {
      "id": "1reDRBNCg48JWY-KSDp-blAi56vJMKnyX",
      "name": "More-Posters",
      "description": ""
    },
    "items": [
      {
        "id": "1GgTHYwWPST4KV3KMrkBqZUsnSL5pkQYe",
        "img": "/gallery/1GgTHYwWPST4KV3KMrkBqZUsnSL5pkQYe.jpg",
        "url": "https://drive.google.com/file/d/1GgTHYwWPST4KV3KMrkBqZUsnSL5pkQYe/view",
        "height": 800,
        "description": ""
      },
      {
        "id": "1owopgmSy7buNiBlspK01xEOOqd4CE56E",
        "img": "/gallery/1owopgmSy7buNiBlspK01xEOOqd4CE56E.png",
        "url": "https://drive.google.com/file/d/1owopgmSy7buNiBlspK01xEOOqd4CE56E/view",
        "height": 877,
        "description": ""
      }
    ]
  },
  {
    "folder": {
      "id": "16t29tmGrDwBXoJsDSzEfbhjGbmkS7MxN",
      "name": "Olympics-2040",
      "description": ""
    },
    "items": [
      {
        "id": "1fXB1HkM-cZpAsjSN0ycRwEuF_7cyQrtJ",
        "img": "/gallery/1fXB1HkM-cZpAsjSN0ycRwEuF_7cyQrtJ.gif",
        "url": "https://drive.google.com/file/d/1fXB1HkM-cZpAsjSN0ycRwEuF_7cyQrtJ/view",
        "height": 600,
        "description": ""
      },
      {
        "id": "1PixfbXYedX9hcmoYMCCJ6ok8wit_3TwF",
        "img": "/gallery/1PixfbXYedX9hcmoYMCCJ6ok8wit_3TwF.png",
        "url": "https://drive.google.com/file/d/1PixfbXYedX9hcmoYMCCJ6ok8wit_3TwF/view",
        "height": 450,
        "description": ""
      },
      {
        "id": "1vY36Y6c1EH_7Jz2fO_DvIOHfasLQU7C1",
        "img": "/gallery/1vY36Y6c1EH_7Jz2fO_DvIOHfasLQU7C1.png",
        "url": "https://drive.google.com/file/d/1vY36Y6c1EH_7Jz2fO_DvIOHfasLQU7C1/view",
        "height": 791,
        "description": ""
      }
    ]
  },
  {
    "folder": {
      "id": "1-kDig9zYIQTY_PufA2IaVTRBmBa280gM",
      "name": "Grumpy-Enneagram",
      "description": ""
    },
    "items": [
      {
        "id": "1AvN9wUQQiSFh5DuvzzNzkB8RdfiG9-kH",
        "img": "/gallery/1AvN9wUQQiSFh5DuvzzNzkB8RdfiG9-kH.png",
        "url": "https://drive.google.com/file/d/1AvN9wUQQiSFh5DuvzzNzkB8RdfiG9-kH/view",
        "height": 535,
        "description": ""
      },
      {
        "id": "1tXQIvWhoTSgSkQXgZsy538c7dLph1Jpa",
        "img": "/gallery/1tXQIvWhoTSgSkQXgZsy538c7dLph1Jpa.png",
        "url": "https://drive.google.com/file/d/1tXQIvWhoTSgSkQXgZsy538c7dLph1Jpa/view",
        "height": 645,
        "description": ""
      },
      {
        "id": "1c5ohKSNHYm9pP5F92ZkCvqaw8Xtdu_Py",
        "img": "/gallery/1c5ohKSNHYm9pP5F92ZkCvqaw8Xtdu_Py.png",
        "url": "https://drive.google.com/file/d/1c5ohKSNHYm9pP5F92ZkCvqaw8Xtdu_Py/view",
        "height": 539,
        "description": ""
      }
    ]
  },
  {
    "folder": {
      "id": "1czAw9r-arv3xJ8Kvx4a4dzi5tpHhGolK",
      "name": "Laser-Cutting-&-Engraving",
      "description": ""
    },
    "items": [
      {
        "id": "1TZYEMsoiWmFYHVQTkuOChl75VcJ567Nj",
        "img": "/gallery/1TZYEMsoiWmFYHVQTkuOChl75VcJ567Nj.gif",
        "url": "https://drive.google.com/file/d/1TZYEMsoiWmFYHVQTkuOChl75VcJ567Nj/view",
        "height": 1046,
        "description": ""
      },
      {
        "id": "1jqD0l1H66ySoIopgDgHKgL7Q7vy45GVh",
        "img": "/gallery/1jqD0l1H66ySoIopgDgHKgL7Q7vy45GVh.png",
        "url": "https://drive.google.com/file/d/1jqD0l1H66ySoIopgDgHKgL7Q7vy45GVh/view",
        "height": 255,
        "description": ""
      }
    ]
  },
  {
    "folder": {
      "id": "1KP-D1_W-qZCkdPKQsLyxYM76wtwFYyuC",
      "name": "Drawings",
      "description": ""
    },
    "items": [
      {
        "id": "1dNJtJFK_4LJbDoBsD5O0Ro3uEE1kJlTk",
        "img": "/gallery/1dNJtJFK_4LJbDoBsD5O0Ro3uEE1kJlTk.png",
        "url": "https://drive.google.com/file/d/1dNJtJFK_4LJbDoBsD5O0Ro3uEE1kJlTk/view",
        "height": 1067,
        "description": ""
      },
      {
        "id": "1FCq0ueL5R0u1BLW_3m3DVTwwPhRKNd13",
        "img": "/gallery/1FCq0ueL5R0u1BLW_3m3DVTwwPhRKNd13.jpg",
        "url": "https://drive.google.com/file/d/1FCq0ueL5R0u1BLW_3m3DVTwwPhRKNd13/view",
        "height": 800,
        "description": ""
      },
      {
        "id": "1bOY2ru8R8SKDE7K3SKHh-GZGeZV8j-KP",
        "img": "/gallery/1bOY2ru8R8SKDE7K3SKHh-GZGeZV8j-KP.gif",
        "url": "https://drive.google.com/file/d/1bOY2ru8R8SKDE7K3SKHh-GZGeZV8j-KP/view",
        "height": 795,
        "description": ""
      },
      {
        "id": "1V6yMQFokl3fZqMbrBqoTiSUHsa9u6a-C",
        "img": "/gallery/1V6yMQFokl3fZqMbrBqoTiSUHsa9u6a-C.gif",
        "url": "https://drive.google.com/file/d/1V6yMQFokl3fZqMbrBqoTiSUHsa9u6a-C/view",
        "height": 822,
        "description": ""
      }
    ]
  },
  {
    "folder": {
      "id": "1_JENwRXBW64f4nqaFoYYS3c8t-5D_WAf",
      "name": "Type-Hike",
      "description": ""
    },
    "items": [
      {
        "id": "1_eWjHaHC_GOmOpuIxsBAzOmZWlqBpROn",
        "img": "/gallery/1_eWjHaHC_GOmOpuIxsBAzOmZWlqBpROn.jpg",
        "url": "https://drive.google.com/file/d/1_eWjHaHC_GOmOpuIxsBAzOmZWlqBpROn/view",
        "height": 800,
        "description": ""
      },
      {
        "id": "1UwgNbG3MNPGAhSIGQvrIRNbv5m_G5vr9",
        "img": "/gallery/1UwgNbG3MNPGAhSIGQvrIRNbv5m_G5vr9.jpg",
        "url": "https://drive.google.com/file/d/1UwgNbG3MNPGAhSIGQvrIRNbv5m_G5vr9/view",
        "height": 800,
        "description": ""
      },
      {
        "id": "1wL2dpf7B6LAWo9NL_kM0umZa3NTjEDBJ",
        "img": "/gallery/1wL2dpf7B6LAWo9NL_kM0umZa3NTjEDBJ.gif",
        "url": "https://drive.google.com/file/d/1wL2dpf7B6LAWo9NL_kM0umZa3NTjEDBJ/view",
        "height": 800,
        "description": ""
      }
    ]
  },
  {
    "folder": {
      "id": "1wxn7hWucCNNkUTZiiIuTo5pdlJTrYgN8",
      "name": "Recipe-Zine",
      "description": ""
    },
    "items": [
      {
        "id": "1SOWd9e6cG9PDwhkvZ_qGx3UMkz5b9rlj",
        "img": "/gallery/1SOWd9e6cG9PDwhkvZ_qGx3UMkz5b9rlj.png",
        "url": "https://drive.google.com/file/d/1SOWd9e6cG9PDwhkvZ_qGx3UMkz5b9rlj/view",
        "height": 464,
        "description": ""
      },
      {
        "id": "1XBO8Jt09vtZpdBRxb6uCMaQPbdsz9DC3",
        "img": "/gallery/1XBO8Jt09vtZpdBRxb6uCMaQPbdsz9DC3.png",
        "url": "https://drive.google.com/file/d/1XBO8Jt09vtZpdBRxb6uCMaQPbdsz9DC3/view",
        "height": 464,
        "description": ""
      },
      {
        "id": "1_QximM5NJjLc4G07_vrhXvcM1PnAKICX",
        "img": "/gallery/1_QximM5NJjLc4G07_vrhXvcM1PnAKICX.png",
        "url": "https://drive.google.com/file/d/1_QximM5NJjLc4G07_vrhXvcM1PnAKICX/view",
        "height": 464,
        "description": ""
      },
      {
        "id": "1-4bNjq0FV7uO8dCD8xk0iFLh_ofwG3zU",
        "img": "/gallery/1-4bNjq0FV7uO8dCD8xk0iFLh_ofwG3zU.png",
        "url": "https://drive.google.com/file/d/1-4bNjq0FV7uO8dCD8xk0iFLh_ofwG3zU/view",
        "height": 464,
        "description": ""
      },
      {
        "id": "1z5aKN2b2f2mx61Naf4ydMPyGKJkDvwnb",
        "img": "/gallery/1z5aKN2b2f2mx61Naf4ydMPyGKJkDvwnb.gif",
        "url": "https://drive.google.com/file/d/1z5aKN2b2f2mx61Naf4ydMPyGKJkDvwnb/view",
        "height": 600,
        "description": ""
      }
    ]
  }
];

/** Flat list of all items (for backwards compatibility). */
export const galleryItems: GalleryItem[] = galleryGroups.flatMap(g => g.items);
